package com.jqsd.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_yf_admin", "id", Admin.class);
		// Composite Primary Key order: aId,mId
		arp.addMapping("t_yf_admin_menu", "aId,mId", AdminMenu.class);
		arp.addMapping("t_yf_db_config", "id", DbConfig.class);
		arp.addMapping("t_yf_job_log", "id", JobLog.class);
		arp.addMapping("t_yf_module", "id", Module.class);
		arp.addMapping("t_yf_org_config", "ownNo", OrgConfig.class);
		arp.addMapping("t_yf_role", "id", Role.class);
		arp.addMapping("t_yf_schedule_job", "id", ScheduleJob.class);
	}
}

