package com.jqsd.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jqsd.common.model.base.BaseAdminMenu;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMenu  extends BaseAdminMenu<AdminMenu> {
	public static final AdminMenu dao = new AdminMenu().dao();

	public boolean deleteByAid(String aId){
		return Db.update("delete from t_yf_admin_menu where aId=?",aId)>0;
	}

	public boolean deleteById(String aId,String omId){
		return Db.update("delete from t_yf_admin_menu where aId=? and mId in ("+omId+")",aId)>0;
	}

	public boolean saveAdminMenuByRole(String aId,String role){
		List<String> list = Db.query("select mId from t_yf_role where id in ("+role+")");
		list.stream().forEach(mId -> saveUserMenu(aId,mId) );
		return true;
	}

	public boolean saveUserMenu(String aId,String mId){
		String[] id = mId.split(",");


//		StringBuilder sql = new StringBuilder();
//		for(int i=0;i<id.length;i++){
//			if(i>0){
//				sql.append(",");
//			}
//			sql.append("('").append(aId).append("',").append(id[i]).append(")");
//		}
//		return Db.update("insert ignore into t_yf_admin_menu values "+sql.toString())>0;

		for(int i=0;i<id.length;i++){
			try {
				Db.update("insert into t_yf_admin_menu values(?,?) ",aId,id[i]);
			} catch (Exception e){
			}
		}

		return true;
	}
}
