package com.jqsd.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.jqsd.common.model.base.BaseDbConfig;
import com.jqsd.common.vo.QueryParamVo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbConfig extends BaseDbConfig<DbConfig> {
	public static final DbConfig dao = new DbConfig().dao();

	public Page<DbConfig> getPage(QueryParamVo vo){
		StringBuilder sql = new StringBuilder();
		sql.append("from t_yf_db_config ");

		return this.paginate(vo.getPageNumber(),vo.getPageSize(),"select * ",sql.toString());
	}

	public List<DbConfig> findAll(){
		return this.find("select * from t_yf_db_config");
	}
}
