package com.jqsd.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.jqsd.common.model.base.BaseModule;
import com.jqsd.common.util.StrUtil;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Module extends BaseModule<Module> {
	public static final Module dao = new Module().dao();

	public boolean saveMenu(Module module){
		if(module.getId()!=null && module.getId()>0){
			return module.update();
		}else {
			return module.remove("id").save();
		}
	}

	public List<Record> getMenuList(){
		return Db.find("select id,pId, name,icon,sn,url as href, is_use,description,priority, case id when 1 then 'true' else 'false ' end as [open] from t_yf_module order by priority ");
	}


	public List<Record> getMenuByLevel(int level){
		return Db.find("select id,name from t_yf_module where level=?",level);
	}

	public List<Record> getMenuListByUserId(String id){
		return Db.find("select a.id,a.pId,a.name,case aId when null then 0 else 1 end  as checked,case id when 1 then '1' else '0 ' end as [open] from t_yf_module a left join t_yf_admin_menu b on a.id=b.mId and b.aId=? where a.is_use=1 order by a.priority ",id);
	}

	public List<Record> getMenuListByRoleId(String id){
		if(StrUtil.isNotBlank(id)){
			String mId = Db.queryStr("select mId From t_yf_role where id=?",id);
			if(StrUtil.isBlank(mId)) mId = "-1";
			return Db.find("select a.id,a.pId,a.name,case when id in ("+mId+") then 1 else 0 end as checked,case a.id when 1 then '1' else '0 ' end as [open] from t_yf_module a where a.is_use=1 order by a.priority ");
		}else{
			return Db.find("select a.id,a.pId,a.name,case id when 1 then '1' else '0 ' end as [open] from t_yf_module a where a.is_use=1 order by a.priority ");
		}
	}

	public List<Record> getModuleAllByTree() {
		return Db.find("select id,pId,name,CASE WHEN LEFT(url,4)='http' THEN  url ELSE '/jqsd'+url END as url ,sn,level,icon from t_yf_module where is_use=1  order by priority asc ");

	}

	public List<Record> getModuleByAid(String aId){
		String sql = "select id,pId,name,CASE WHEN LEFT(url,4)='http' THEN  url ELSE '/jqsd'+url END as url,sn,level,icon from t_yf_module a left join t_yf_admin_menu b on a.id=b.mId where is_use=1 and b.aId=? order by priority asc";
		return Db.find(sql,aId);
	}
}
