package com.jqsd.common.model;

import com.jqsd.common.model.base.BaseOrgConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrgConfig extends BaseOrgConfig<OrgConfig> {
	public static final OrgConfig dao = new OrgConfig().dao();

}
