package com.jqsd.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jqsd.common.model.base.BaseRole;
import com.jqsd.common.util.StrUtil;
import com.jqsd.common.vo.QueryParamVo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role().dao();

	public List<Role> findAll(){
		return dao.find("select id,roleName from t_yf_role ");
	}

	public Page<Record> getRoleList(QueryParamVo queryParamVo){
		String sql=" from t_yf_role  where 1=1  ";
		if(StrUtil.isNotBlank(queryParamVo.getName())){
			sql+=" and roleName like '%"+queryParamVo.getName()+"%' ";
		}
		return Db.paginate(queryParamVo.getPageNumber(), queryParamVo.getPageSize(),"select * ",sql);
	}
}
