package com.jqsd.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jqsd.common.AppConfig;
import com.jqsd.common.model.base.BaseScheduleJob;
import com.jqsd.common.util.StrUtil;
import com.jqsd.common.vo.QueryParamVo;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScheduleJob extends BaseScheduleJob<ScheduleJob> {
	public static final ScheduleJob dao = new ScheduleJob().dao();

	public boolean saveJob(ScheduleJob job){
		if(job.getId()!=null){
			return job.update();
		}else{
			AppConfig.addJob(job);
			return job.setCreateTime(new Date()).remove("id").save();
		}
	}

	public Page<Record> getJobList(QueryParamVo queryParamVo){
		String sql=" from t_yf_schedule_job a left join t_yf_db_config b on a.dbId=b.id  where 1=1  ";
		if(StrUtil.isNotBlank(queryParamVo.getName())){
			sql+=" and a.name like '%"+queryParamVo.getName()+"%' ";
		}
		return Db.paginate(queryParamVo.getPageNumber(), queryParamVo.getPageSize(),"select a.*,b.dbName ",sql);
	}

	public boolean updateStatus(QueryParamVo vo){
		return Db.update("update t_yf_schedule_job set status = ? where id = ?",vo.getStatus(),vo.getId())>0;
	}

	public boolean startJob(long id){
		return Db.update("update t_yf_schedule_job set param='running' where id = ? and param='stop' ",id)>0;
	}

	public boolean stopJob(long id){
		return Db.update("update t_yf_schedule_job set param='stop' ,updateTime = GETDATE() where id = ?",id)>0;
	}


	public List<ScheduleJob> findAll(){
		return this.find("select * from t_yf_schedule_job where status=1");
	}
}
