package com.jqsd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrgConfig<M extends BaseOrgConfig<M>> extends Model<M> implements IBean {

	public M setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
		return (M)this;
	}

	public java.lang.String getOrgId() {
		return getStr("orgId");
	}

	public M setOrgName(java.lang.String orgName) {
		set("orgName", orgName);
		return (M)this;
	}

	public java.lang.String getOrgName() {
		return getStr("orgName");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}

	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	public M setOwnNo(java.lang.String ownNo) {
		set("ownNo", ownNo);
		return (M)this;
	}

	public java.lang.String getOwnNo() {
		return getStr("ownNo");
	}

	public M setForgId(java.lang.String forgId) {
		set("forgId", forgId);
		return (M)this;
	}

	public java.lang.String getForgId() {
		return getStr("forgId");
	}

}
