package com.jqsd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDbConfig<M extends BaseDbConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setDbType(java.lang.String dbType) {
		set("dbType", dbType);
		return (M)this;
	}

	public java.lang.String getDbType() {
		return getStr("dbType");
	}

	public M setDbName(java.lang.String dbName) {
		set("dbName", dbName);
		return (M)this;
	}

	public java.lang.String getDbName() {
		return getStr("dbName");
	}

	public M setDbUrl(java.lang.String dbUrl) {
		set("dbUrl", dbUrl);
		return (M)this;
	}

	public java.lang.String getDbUrl() {
		return getStr("dbUrl");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setPort(java.lang.String port) {
		set("port", port);
		return (M)this;
	}

	public java.lang.String getPort() {
		return getStr("port");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}

	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setDbId(java.lang.String dbId) {
		set("dbId", dbId);
		return (M)this;
	}

	public java.lang.String getDbId() {
		return getStr("dbId");
	}

}
