package com.jqsd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseScheduleJob<M extends BaseScheduleJob<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCron(java.lang.String cron) {
		set("cron", cron);
		return (M)this;
	}

	public java.lang.String getCron() {
		return getStr("cron");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setJobClass(java.lang.String jobClass) {
		set("jobClass", jobClass);
		return (M)this;
	}

	public java.lang.String getJobClass() {
		return getStr("jobClass");
	}

	public M setDbId(java.lang.String dbId) {
		set("dbId", dbId);
		return (M)this;
	}

	public java.lang.String getDbId() {
		return getStr("dbId");
	}

	public M setParam(java.lang.String param) {
		set("param", param);
		return (M)this;
	}

	public java.lang.String getParam() {
		return getStr("param");
	}

	public M setMin(java.lang.String min) {
		set("min", min);
		return (M)this;
	}

	public java.lang.String getMin() {
		return getStr("min");
	}

	public M setHour(java.lang.String hour) {
		set("hour", hour);
		return (M)this;
	}

	public java.lang.String getHour() {
		return getStr("hour");
	}

	public M setDay(java.lang.String day) {
		set("day", day);
		return (M)this;
	}

	public java.lang.String getDay() {
		return getStr("day");
	}

	public M setMon(java.lang.String mon) {
		set("mon", mon);
		return (M)this;
	}

	public java.lang.String getMon() {
		return getStr("mon");
	}

	public M setWeek(java.lang.String week) {
		set("week", week);
		return (M)this;
	}

	public java.lang.String getWeek() {
		return getStr("week");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
