package com.jqsd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminMenu<M extends BaseAdminMenu<M>> extends Model<M> implements IBean {

	public M setAId(java.lang.String aId) {
		set("aId", aId);
		return (M)this;
	}

	public java.lang.String getAId() {
		return getStr("aId");
	}

	public M setMId(java.lang.Integer mId) {
		set("mId", mId);
		return (M)this;
	}

	public java.lang.Integer getMId() {
		return getInt("mId");
	}

}
